name: Check - Enforce all checks pass
on:
  pull_request:

jobs:
  enforce-all-checks:
    name: Enforce all checks pass
    uses: nikobockerman/github-actions/.github/workflows/check-enforce-all-checks.yaml@7b1af6f4c86875452a3c50b3d7ebdc25fa5a5010 # v1
    permissions:
      checks: read
