name: Check - Renovate config
on:
  workflow_call:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  renovate-config-validator:
    name: Renovate config validator
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Renovate config validator
        run: |
          npx --package=renovate --yes -- \
            renovate-config-validator --strict \
            *.json5 \
            default.json \
            .github/renovate.json5
