name: Check - Renovate config
on:
  pull_request:
    paths:
      - "*.json5"
      - "default.json"
      - ".github/renovate.json5"
      - ".github/workflows/check-renovate-config.yaml"
      - "package.json"
  workflow_call:
  workflow_dispatch:

jobs:
  renovate-config-validator:
    name: Renovate config validator
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup project
        uses: ./.github/actions/yarn-project-setup
      - name: Renovate config validator
        run: yarn run check:renovateconfig
