name: Check - Enforce all checks pass
on:
  pull_request:

jobs:
  wf:
    uses: nikobockerman/github-workflows/.github/workflows/check-enforce-all-checks.yaml@43aca657d9f7a3a58efdf9e2b33668a0f4b6fb6e
    permissions:
      checks: read
