name: Check - Github actions
on:
  pull_request:
    paths:
      - ".github/workflows/**.yaml"
      - ".github/actions/**"
      - "package.json"
      - "yarn.lock"
  workflow_dispatch:

jobs:
  wf:
    uses: nikobockerman/github-actions/.github/workflows/check-github-actions.yaml@c75aeec4bead81a5a8f4b50a1de3b14a2a397e4d
