name: CI
on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    # Run every Monday at 00:30 UTC
    - cron: "30 0 * * 1"
  workflow_dispatch:
permissions:
  contents: read

jobs:
  mise-cache:
    uses: nikobockerman/github-workflows/.github/workflows/mise-prepare-cache.yaml@340aec64780796686d2c5a09dc5285dffb437970 # v1.0.18
  check-prettier:
    needs: mise-cache
    uses: nikobockerman/github-workflows/.github/workflows/mise-task.yaml@340aec64780796686d2c5a09dc5285dffb437970 # v1.0.18
    with:
      task: check:prettier
  check-renovate-config:
    needs: mise-cache
    uses: nikobockerman/github-workflows/.github/workflows/mise-task.yaml@340aec64780796686d2c5a09dc5285dffb437970 # v1.0.18
    with:
      task: check:renovateconfig

  check:
    needs:
      - check-prettier
      - check-renovate-config
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: re-actors/alls-green@05ac9388f0aebcb5727afa17fcccfecd6f8ec5fe # v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
