name: CI

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - ".github/workflows/ci.yaml"
  schedule:
    # Run every Monday at 00:30 UTC
    - cron: "30 0 * * 1"
  workflow_dispatch:

jobs:
  check-github-actions:
    uses: nikobockerman/github-workflows/.github/workflows/check-github-actions.yaml@c40fd048af4cc60e443fb5e0741812d69716d6a6
  check-prettier:
    uses: nikobockerman/github-workflows/.github/workflows/check-prettier.yaml@c40fd048af4cc60e443fb5e0741812d69716d6a6
  check-renovate-config:
    uses: ./.github/workflows/check-renovate-config.yaml
  check-yarn:
    uses: nikobockerman/github-workflows/.github/workflows/check-yarn.yaml@c40fd048af4cc60e443fb5e0741812d69716d6a6
