name: CI
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - ".github/workflows/ci.yaml"
  schedule:
    # Run every Monday at 00:30 UTC
    - cron: "30 0 * * 1"
  workflow_dispatch:
permissions:
  contents: read

jobs:
  check-github-actions:
    uses: nikobockerman/github-workflows/.github/workflows/check-github-actions.yaml@00f3fa57247684c3937dfdda879ff0f6e95584e4
  check-prettier:
    uses: nikobockerman/github-workflows/.github/workflows/check-prettier.yaml@00f3fa57247684c3937dfdda879ff0f6e95584e4
  check-renovate-config:
    uses: ./.github/workflows/check-renovate-config.yaml
  check-yarn:
    uses: nikobockerman/github-workflows/.github/workflows/check-yarn.yaml@00f3fa57247684c3937dfdda879ff0f6e95584e4
